### ISSUE TITLE
Tooling failing for 22.x

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs-dependency-vuln-assessments#185]
```shell
Traceback (most recent call last):
  File "/home/runner/work/nodejs-dependency-vuln-assessments/nodejs-dependency-vuln-assessments/dep_checker/main.py", line 261, in <module>
    exit(main())
  File "/home/runner/work/nodejs-dependency-vuln-assessments/nodejs-dependency-vuln-assessments/dep_checker/main.py", line 2[16](https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/8843384012/job/24283715415#step:6:17), in main
    raise RuntimeError(
RuntimeError: Invalid argument: 'v22.x' is not a supported branch. Please use one of: ['main', 'v21.x', 'v20.x', 'v[18](https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/8843384012/job/24283715415#step:6:19).x']
Error: Process completed with exit code 1.
```

**Comment by mhdawson** [comment]
@richardlau do you know off the top of your head why this might happen. If not I'll take a closer look but for some reason I think you might know without looking.

**Comment by targos** [comment]
v22.x is not here https://github.com/nodejs/nodejs-dependency-vuln-assessments/blob/0e60f0c0303cd628b4731820503533cc1703c2d4/dep_checker/dependencies.py#L60-L65
