### ISSUE TITLE
Check job failing.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs-dependency-vuln-assessments#96]
The check job started failing 2 days ago - https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3717467618

```shell
Run (
Traceback (most recent call last):
  File "/home/runner/work/nodejs-dependency-vuln-assessments/nodejs-dependency-vuln-assessments/dep_checker/main.py", line 261, in <module>
    exit(main())
  File "/home/runner/work/nodejs-dependency-vuln-assessments/nodejs-dependency-vuln-assessments/dep_checker/main.py", line 236, in main
    nvd_vulnerabilities: list[Vulnerability] = query_nvd(
  File "/home/runner/work/nodejs-dependency-vuln-assessments/nodejs-dependency-vuln-assessments/dep_checker/main.py", line [15](https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3717467618/jobs/6304891898#step:6:16)5, in query_nvd
    for cve in searchCVE(
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3717467618/jobs/6304891898#step:6:17)/x64/lib/python3.9/site-packages/nvdlib/cve.py", line 274, in searchCVE
    cves.append(__convert('cve', eachCVE['cve']))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nvdlib/classes.py", line 200, in __convert
    vuln.getvars()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nvdlib/classes.py", line [18](https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3717467618/jobs/6304891898#step:6:19)1, in getvars
    self.v2severity = self.metrics.cvssMetricV2[0].cvssData.baseSeverity
AttributeError: 'CVE' object has no attribute 'baseSeverity'
```

**Comment by mhdawson** [comment]
Looks related to https://github.com/vehemont/nvdlib/issues/16

**Comment by mhdawson** [comment]
Kicked off action to test - https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3733272412/jobs/6333849271
